version: 2

project_name: agentpane

builds:
  - id: agentpane
    main: ./cmd/agentpane
    binary: agentpane
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

brews:
  - name: agentpane
    repository:
      owner: minghinmatthewlam
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/minghinmatthewlam/agentpane
    description: tmux-based environment for managing AI coding agent panes
    license: MIT
    install: |
      bin.install "agentpane"
    test: |
      system "#{bin}/agentpane", "--help"
